package com.sweet.selfiecameraphotoeditor.collageutils.collageviews;

import android.graphics.PointF;

import com.sweet.selfiecameraphotoeditor.collageutils.PhotoItem;
import com.sweet.selfiecameraphotoeditor.collageutils.TemplateItem;

import java.util.HashMap;

public class EightFrameImage {
    static TemplateItem collage816() {
        TemplateItem collage = FrameImageUtils.collage("collage_8_16.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.shrinkMethod = 5;
        photoItem.bound.set(0.0f, 0.0f, 0.5f, 0.5f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.shrinkMap = new HashMap<>();
        photoItem.shrinkMap.put(photoItem.pointList.get(0), new PointF(1.0f, 2.0f));
        photoItem.shrinkMap.put(photoItem.pointList.get(1), new PointF(2.0f, 1.0f));
        photoItem.shrinkMap.put(photoItem.pointList.get(2), new PointF(1.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.shrinkMethod = 5;
        photoItem2.bound.set(0.0f, 0.0f, 0.5f, 0.5f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        photoItem2.shrinkMap = new HashMap<>();
        photoItem2.shrinkMap.put(photoItem2.pointList.get(0), new PointF(2.0f, 1.0f));
        photoItem2.shrinkMap.put(photoItem2.pointList.get(1), new PointF(1.0f, 1.0f));
        photoItem2.shrinkMap.put(photoItem2.pointList.get(2), new PointF(1.0f, 2.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.shrinkMethod = 5;
        photoItem3.bound.set(0.5f, 0.0f, 1.0f, 0.5f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        photoItem3.shrinkMap = new HashMap<>();
        photoItem3.shrinkMap.put(photoItem3.pointList.get(0), new PointF(1.0f, 2.0f));
        photoItem3.shrinkMap.put(photoItem3.pointList.get(1), new PointF(2.0f, 1.0f));
        photoItem3.shrinkMap.put(photoItem3.pointList.get(2), new PointF(1.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.shrinkMethod = 5;
        photoItem4.bound.set(0.5f, 0.0f, 1.0f, 0.5f);
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        photoItem4.shrinkMap = new HashMap<>();
        photoItem4.shrinkMap.put(photoItem4.pointList.get(0), new PointF(1.0f, 2.0f));
        photoItem4.shrinkMap.put(photoItem4.pointList.get(1), new PointF(2.0f, 1.0f));
        photoItem4.shrinkMap.put(photoItem4.pointList.get(2), new PointF(1.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.shrinkMethod = 5;
        photoItem5.bound.set(0.0f, 0.5f, 0.5f, 1.0f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        photoItem5.shrinkMap = new HashMap<>();
        photoItem5.shrinkMap.put(photoItem5.pointList.get(0), new PointF(2.0f, 1.0f));
        photoItem5.shrinkMap.put(photoItem5.pointList.get(1), new PointF(1.0f, 1.0f));
        photoItem5.shrinkMap.put(photoItem5.pointList.get(2), new PointF(1.0f, 2.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.shrinkMethod = 5;
        photoItem6.bound.set(0.0f, 0.5f, 0.5f, 1.0f);
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        photoItem6.shrinkMap = new HashMap<>();
        photoItem6.shrinkMap.put(photoItem6.pointList.get(0), new PointF(1.0f, 1.0f));
        photoItem6.shrinkMap.put(photoItem6.pointList.get(1), new PointF(1.0f, 2.0f));
        photoItem6.shrinkMap.put(photoItem6.pointList.get(2), new PointF(2.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 6;
        photoItem7.shrinkMethod = 5;
        photoItem7.bound.set(0.5f, 0.5f, 1.0f, 1.0f);
        photoItem7.pointList.add(new PointF(0.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        photoItem7.shrinkMap = new HashMap<>();
        photoItem7.shrinkMap.put(photoItem7.pointList.get(0), new PointF(1.0f, 1.0f));
        photoItem7.shrinkMap.put(photoItem7.pointList.get(1), new PointF(1.0f, 2.0f));
        photoItem7.shrinkMap.put(photoItem7.pointList.get(2), new PointF(2.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        PhotoItem photoItem8 = new PhotoItem();
        photoItem8.index = 7;
        photoItem8.shrinkMethod = 5;
        photoItem8.bound.set(0.5f, 0.5f, 1.0f, 1.0f);
        photoItem8.pointList.add(new PointF(0.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 1.0f));
        photoItem8.shrinkMap = new HashMap<>();
        photoItem8.shrinkMap.put(photoItem8.pointList.get(0), new PointF(1.0f, 1.0f));
        photoItem8.shrinkMap.put(photoItem8.pointList.get(1), new PointF(1.0f, 2.0f));
        photoItem8.shrinkMap.put(photoItem8.pointList.get(2), new PointF(2.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem8);
        return collage;
    }

    static TemplateItem collage815() {
        TemplateItem collage = FrameImageUtils.collage("collage_8_15.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.3333f, 0.3333f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.3333f, 0.0f, 0.6666f, 0.3333f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.6666f, 0.0f, 1.0f, 0.3333f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.0f, 0.3333f, 0.6666f, 0.6666f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.6666f, 0.3333f, 1.0f, 0.6666f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.0f, 0.6666f, 0.3333f, 1.0f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 6;
        photoItem7.bound.set(0.3333f, 0.6666f, 0.6666f, 1.0f);
        photoItem7.pointList.add(new PointF(0.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        PhotoItem photoItem8 = new PhotoItem();
        photoItem8.index = 7;
        photoItem8.bound.set(0.6666f, 0.6666f, 1.0f, 1.0f);
        photoItem8.pointList.add(new PointF(0.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 1.0f));
        photoItem8.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem8);
        return collage;
    }

    static TemplateItem collage814() {
        TemplateItem collage = FrameImageUtils.collage("collage_8_14.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.3333f, 0.3333f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.3333f, 0.0f, 0.6666f, 0.3333f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.6666f, 0.0f, 1.0f, 0.3333f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.0f, 0.3333f, 0.3333f, 0.6666f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.3333f, 0.3333f, 1.0f, 0.6666f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.0f, 0.6666f, 0.3333f, 1.0f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 6;
        photoItem7.bound.set(0.3333f, 0.6666f, 0.6666f, 1.0f);
        photoItem7.pointList.add(new PointF(0.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        PhotoItem photoItem8 = new PhotoItem();
        photoItem8.index = 7;
        photoItem8.bound.set(0.6666f, 0.6666f, 1.0f, 1.0f);
        photoItem8.pointList.add(new PointF(0.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 1.0f));
        photoItem8.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem8);
        return collage;
    }

    static TemplateItem collage813() {
        TemplateItem collage = FrameImageUtils.collage("collage_8_13.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.3333f, 0.25f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.3333f, 0.0f, 0.6666f, 0.25f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.6666f, 0.0f, 1.0f, 0.25f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.0f, 0.25f, 1.0f, 0.5f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.0f, 0.5f, 1.0f, 0.75f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.0f, 0.75f, 0.3333f, 1.0f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 6;
        photoItem7.bound.set(0.3333f, 0.75f, 0.6666f, 1.0f);
        photoItem7.pointList.add(new PointF(0.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        PhotoItem photoItem8 = new PhotoItem();
        photoItem8.index = 7;
        photoItem8.bound.set(0.6666f, 0.75f, 1.0f, 1.0f);
        photoItem8.pointList.add(new PointF(0.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 1.0f));
        photoItem8.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem8);
        return collage;
    }

    static TemplateItem collage812() {
        TemplateItem collage = FrameImageUtils.collage("collage_8_12.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.6666f, 0.25f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.6666f, 0.0f, 1.0f, 0.25f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.0f, 0.25f, 0.3333f, 0.5f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.3333f, 0.25f, 1.0f, 0.5f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.0f, 0.5f, 0.6666f, 0.75f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.6666f, 0.5f, 1.0f, 0.75f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 6;
        photoItem7.bound.set(0.0f, 0.75f, 0.3333f, 1.0f);
        photoItem7.pointList.add(new PointF(0.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        PhotoItem photoItem8 = new PhotoItem();
        photoItem8.index = 7;
        photoItem8.bound.set(0.3333f, 0.75f, 1.0f, 1.0f);
        photoItem8.pointList.add(new PointF(0.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 1.0f));
        photoItem8.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem8);
        return collage;
    }

    static TemplateItem collage811() {
        TemplateItem collage = FrameImageUtils.collage("collage_8_11.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.5f, 0.25f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.5f, 0.0f, 1.0f, 0.25f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.0f, 0.25f, 0.5f, 0.5f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.5f, 0.25f, 1.0f, 0.5f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.0f, 0.5f, 0.6666f, 0.75f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.6666f, 0.5f, 1.0f, 0.75f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 6;
        photoItem7.bound.set(0.0f, 0.75f, 0.3333f, 1.0f);
        photoItem7.pointList.add(new PointF(0.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        PhotoItem photoItem8 = new PhotoItem();
        photoItem8.index = 7;
        photoItem8.bound.set(0.3333f, 0.75f, 1.0f, 1.0f);
        photoItem8.pointList.add(new PointF(0.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 1.0f));
        photoItem8.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem8);
        return collage;
    }

    static TemplateItem collage810() {
        TemplateItem collage = FrameImageUtils.collage("collage_8_10.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.5f, 0.25f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.5f, 0.0f, 1.0f, 0.25f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.0f, 0.25f, 0.5f, 0.5f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.5f, 0.25f, 1.0f, 0.5f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.0f, 0.5f, 0.5f, 0.75f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.5f, 0.5f, 1.0f, 0.75f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 6;
        photoItem7.bound.set(0.0f, 0.75f, 0.5f, 1.0f);
        photoItem7.pointList.add(new PointF(0.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        PhotoItem photoItem8 = new PhotoItem();
        photoItem8.index = 7;
        photoItem8.bound.set(0.5f, 0.75f, 1.0f, 1.0f);
        photoItem8.pointList.add(new PointF(0.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 1.0f));
        photoItem8.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem8);
        return collage;
    }

    static TemplateItem collage89() {
        TemplateItem collage = FrameImageUtils.collage("collage_8_9.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.3333f, 0.25f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.3333f, 0.0f, 0.6666f, 0.25f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.6666f, 0.0f, 1.0f, 0.25f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.0f, 0.25f, 0.3333f, 0.5f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.3333f, 0.25f, 0.6666f, 0.5f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.6666f, 0.25f, 1.0f, 0.5f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 6;
        photoItem7.bound.set(0.0f, 0.5f, 0.6666f, 1.0f);
        photoItem7.pointList.add(new PointF(0.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        PhotoItem photoItem8 = new PhotoItem();
        photoItem8.index = 7;
        photoItem8.bound.set(0.6666f, 0.5f, 1.0f, 1.0f);
        photoItem8.pointList.add(new PointF(0.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 1.0f));
        photoItem8.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem8);
        return collage;
    }

    static TemplateItem collage88() {
        TemplateItem collage = FrameImageUtils.collage("collage_8_8.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.3333f, 0.25f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.3333f, 0.0f, 0.6666f, 0.25f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.0f, 0.25f, 0.6666f, 0.7f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.0f, 0.7f, 0.6666f, 1.0f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.6666f, 0.0f, 1.0f, 0.25f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.6666f, 0.25f, 1.0f, 0.5f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 6;
        photoItem7.bound.set(0.6666f, 0.5f, 1.0f, 0.75f);
        photoItem7.pointList.add(new PointF(0.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        PhotoItem photoItem8 = new PhotoItem();
        photoItem8.index = 7;
        photoItem8.bound.set(0.6666f, 0.75f, 1.0f, 1.0f);
        photoItem8.pointList.add(new PointF(0.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 1.0f));
        photoItem8.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem8);
        return collage;
    }

    static TemplateItem collage87() {
        TemplateItem collage = FrameImageUtils.collage("collage_8_7.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.3f, 0.2f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.3f, 0.0f, 0.6f, 0.2f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.0f, 0.2f, 0.3f, 0.6f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.3f, 0.2f, 0.6f, 0.6f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.0f, 0.6f, 0.6f, 1.0f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.6f, 0.0f, 1.0f, 0.3333f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 6;
        photoItem7.bound.set(0.6f, 0.3333f, 1.0f, 0.6666f);
        photoItem7.pointList.add(new PointF(0.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        PhotoItem photoItem8 = new PhotoItem();
        photoItem8.index = 7;
        photoItem8.bound.set(0.6f, 0.6666f, 1.0f, 1.0f);
        photoItem8.pointList.add(new PointF(0.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 1.0f));
        photoItem8.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem8);
        return collage;
    }

    static TemplateItem collage86() {
        TemplateItem collage = FrameImageUtils.collage("collage_8_6.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.6f, 0.5f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.6f, 0.0f, 1.0f, 0.3333f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.6f, 0.3333f, 1.0f, 0.6666f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.6f, 0.6666f, 1.0f, 1.0f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.0f, 0.5f, 0.3f, 0.75f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.3f, 0.5f, 0.6f, 0.75f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 6;
        photoItem7.bound.set(0.0f, 0.75f, 0.3f, 1.0f);
        photoItem7.pointList.add(new PointF(0.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        PhotoItem photoItem8 = new PhotoItem();
        photoItem8.index = 7;
        photoItem8.bound.set(0.3f, 0.75f, 0.6f, 1.0f);
        photoItem8.pointList.add(new PointF(0.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 1.0f));
        photoItem8.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem8);
        return collage;
    }

    static TemplateItem collage85() {
        TemplateItem collage = FrameImageUtils.collage("collage_8_5.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.25f, 0.5f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.25f, 0.0f, 0.5f, 0.5f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.5f, 0.0f, 0.75f, 0.5f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.75f, 0.0f, 1.0f, 0.5f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.0f, 0.5f, 0.25f, 1.0f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.25f, 0.5f, 0.5f, 1.0f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 6;
        photoItem7.bound.set(0.5f, 0.5f, 0.75f, 1.0f);
        photoItem7.pointList.add(new PointF(0.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        PhotoItem photoItem8 = new PhotoItem();
        photoItem8.index = 7;
        photoItem8.bound.set(0.75f, 0.5f, 1.0f, 1.0f);
        photoItem8.pointList.add(new PointF(0.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 1.0f));
        photoItem8.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem8);
        return collage;
    }

    static TemplateItem collage84() {
        TemplateItem collage = FrameImageUtils.collage("collage_8_4.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.25f, 0.25f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.0f, 0.25f, 0.25f, 1.0f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.25f, 0.0f, 0.5f, 0.75f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.25f, 0.75f, 0.5f, 1.0f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.5f, 0.0f, 0.75f, 0.25f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.5f, 0.25f, 0.75f, 1.0f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 6;
        photoItem7.bound.set(0.75f, 0.0f, 1.0f, 0.75f);
        photoItem7.pointList.add(new PointF(0.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        PhotoItem photoItem8 = new PhotoItem();
        photoItem8.index = 7;
        photoItem8.bound.set(0.75f, 0.75f, 1.0f, 1.0f);
        photoItem8.pointList.add(new PointF(0.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 1.0f));
        photoItem8.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem8);
        return collage;
    }

    static TemplateItem collage83() {
        TemplateItem collage = FrameImageUtils.collage("collage_8_3.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.25f, 0.25f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.25f, 0.0f, 0.5f, 0.25f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.5f, 0.0f, 1.0f, 0.25f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.0f, 0.25f, 0.5f, 0.75f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.5f, 0.25f, 1.0f, 0.75f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.0f, 0.75f, 0.5f, 1.0f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 6;
        photoItem7.bound.set(0.5f, 0.75f, 0.75f, 1.0f);
        photoItem7.pointList.add(new PointF(0.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        PhotoItem photoItem8 = new PhotoItem();
        photoItem8.index = 7;
        photoItem8.bound.set(0.75f, 0.75f, 1.0f, 1.0f);
        photoItem8.pointList.add(new PointF(0.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 1.0f));
        photoItem8.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem8);
        return collage;
    }

    static TemplateItem collage82() {
        TemplateItem collage = FrameImageUtils.collage("collage_8_2.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.3333f, 0.3333f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.0f, 0.3333f, 0.3333f, 0.6666f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.0f, 0.6666f, 0.3333f, 1.0f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.3333f, 0.0f, 0.6666f, 0.5f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.3333f, 0.5f, 0.6666f, 1.0f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.6666f, 0.0f, 1.0f, 0.3333f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 6;
        photoItem7.bound.set(0.6666f, 0.3333f, 1.0f, 0.6666f);
        photoItem7.pointList.add(new PointF(0.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        PhotoItem photoItem8 = new PhotoItem();
        photoItem8.index = 7;
        photoItem8.bound.set(0.6666f, 0.6666f, 1.0f, 1.0f);
        photoItem8.pointList.add(new PointF(0.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 1.0f));
        photoItem8.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem8);
        return collage;
    }

    static TemplateItem collage81() {
        TemplateItem collage = FrameImageUtils.collage("collage_8_1.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.3333f, 0.3333f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.3333f, 0.0f, 0.6666f, 0.3333f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.6666f, 0.0f, 1.0f, 0.3333f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.0f, 0.3333f, 0.5f, 0.6666f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.5f, 0.3333f, 1.0f, 0.6666f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.0f, 0.6666f, 0.3333f, 1.0f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 6;
        photoItem7.bound.set(0.3333f, 0.6666f, 0.6666f, 1.0f);
        photoItem7.pointList.add(new PointF(0.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        PhotoItem photoItem8 = new PhotoItem();
        photoItem8.index = 7;
        photoItem8.bound.set(0.6666f, 0.6666f, 1.0f, 1.0f);
        photoItem8.pointList.add(new PointF(0.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 1.0f));
        photoItem8.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem8);
        return collage;
    }

    static TemplateItem collage80() {
        TemplateItem collage = FrameImageUtils.collage("collage_8_0.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.25f, 0.5f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.25f, 0.0f, 0.5f, 0.5f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.5f, 0.0f, 1.0f, 0.25f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.5f, 0.25f, 1.0f, 0.5f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.0f, 0.5f, 0.5f, 0.75f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.0f, 0.75f, 0.5f, 1.0f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 6;
        photoItem7.bound.set(0.5f, 0.5f, 0.75f, 1.0f);
        photoItem7.pointList.add(new PointF(0.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        PhotoItem photoItem8 = new PhotoItem();
        photoItem8.index = 7;
        photoItem8.bound.set(0.75f, 0.5f, 1.0f, 1.0f);
        photoItem8.pointList.add(new PointF(0.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 1.0f));
        photoItem8.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem8);
        return collage;
    }
}
