package com.sweet.selfiecameraphotoeditor.collageutils.collageviews;

import android.graphics.PointF;

import com.sweet.selfiecameraphotoeditor.collageutils.PhotoItem;
import com.sweet.selfiecameraphotoeditor.collageutils.TemplateItem;

import java.util.HashMap;

public class NineFrameImage {
    static TemplateItem collage911() {
        TemplateItem collage = FrameImageUtils.collage("collage_9_11.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.shrinkMethod = 5;
        photoItem.bound.set(0.0f, 0.0f, 0.2666f, 0.3333f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(0.7519f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        photoItem.shrinkMap = new HashMap<>();
        photoItem.shrinkMap.put(photoItem.pointList.get(0), new PointF(2.0f, 2.0f));
        photoItem.shrinkMap.put(photoItem.pointList.get(1), new PointF(2.0f, 1.0f));
        photoItem.shrinkMap.put(photoItem.pointList.get(2), new PointF(1.0f, 1.0f));
        photoItem.shrinkMap.put(photoItem.pointList.get(3), new PointF(1.0f, 2.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.shrinkMethod = 5;
        photoItem2.bound.set(0.2f, 0.0f, 0.8f, 0.3333f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(0.8889f, 1.0f));
        photoItem2.pointList.add(new PointF(0.1111f, 1.0f));
        photoItem2.shrinkMap = new HashMap<>();
        photoItem2.shrinkMap.put(photoItem2.pointList.get(0), new PointF(1.0f, 2.0f));
        photoItem2.shrinkMap.put(photoItem2.pointList.get(1), new PointF(2.0f, 1.0f));
        photoItem2.shrinkMap.put(photoItem2.pointList.get(2), new PointF(1.0f, 1.0f));
        photoItem2.shrinkMap.put(photoItem2.pointList.get(3), new PointF(1.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 8;
        photoItem3.shrinkMethod = 5;
        photoItem3.bound.set(0.7334f, 0.0f, 1.0f, 0.3333f);
        photoItem3.pointList.add(new PointF(0.2481f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        photoItem3.shrinkMap = new HashMap<>();
        photoItem3.shrinkMap.put(photoItem3.pointList.get(0), new PointF(1.0f, 2.0f));
        photoItem3.shrinkMap.put(photoItem3.pointList.get(1), new PointF(2.0f, 2.0f));
        photoItem3.shrinkMap.put(photoItem3.pointList.get(2), new PointF(2.0f, 1.0f));
        photoItem3.shrinkMap.put(photoItem3.pointList.get(3), new PointF(1.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 2;
        photoItem4.shrinkMethod = 5;
        photoItem4.bound.set(0.0f, 0.3333f, 0.3333f, 0.6666f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(0.8f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        photoItem4.shrinkMap = new HashMap<>();
        photoItem4.shrinkMap.put(photoItem4.pointList.get(0), new PointF(2.0f, 1.0f));
        photoItem4.shrinkMap.put(photoItem4.pointList.get(1), new PointF(1.0f, 1.0f));
        photoItem4.shrinkMap.put(photoItem4.pointList.get(2), new PointF(1.0f, 1.0f));
        photoItem4.shrinkMap.put(photoItem4.pointList.get(3), new PointF(1.0f, 2.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 3;
        photoItem5.shrinkMethod = 5;
        photoItem5.bound.set(0.2666f, 0.3333f, 0.7334f, 0.6666f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(0.8572f, 1.0f));
        photoItem5.pointList.add(new PointF(0.1428f, 1.0f));
        photoItem5.shrinkMap = new HashMap<>();
        photoItem5.shrinkMap.put(photoItem5.pointList.get(0), new PointF(1.0f, 1.0f));
        photoItem5.shrinkMap.put(photoItem5.pointList.get(1), new PointF(1.0f, 1.0f));
        photoItem5.shrinkMap.put(photoItem5.pointList.get(2), new PointF(1.0f, 1.0f));
        photoItem5.shrinkMap.put(photoItem5.pointList.get(3), new PointF(1.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 4;
        photoItem6.shrinkMethod = 5;
        photoItem6.bound.set(0.6666f, 0.3333f, 1.0f, 0.6666f);
        photoItem6.pointList.add(new PointF(0.2f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        photoItem6.shrinkMap = new HashMap<>();
        photoItem6.shrinkMap.put(photoItem6.pointList.get(0), new PointF(1.0f, 1.0f));
        photoItem6.shrinkMap.put(photoItem6.pointList.get(1), new PointF(1.0f, 2.0f));
        photoItem6.shrinkMap.put(photoItem6.pointList.get(2), new PointF(2.0f, 1.0f));
        photoItem6.shrinkMap.put(photoItem6.pointList.get(3), new PointF(1.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 5;
        photoItem7.shrinkMethod = 5;
        photoItem7.bound.set(0.0f, 0.6666f, 0.4f, 1.0f);
        photoItem7.pointList.add(new PointF(0.0f, 0.0f));
        photoItem7.pointList.add(new PointF(0.8333f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        photoItem7.shrinkMap = new HashMap<>();
        photoItem7.shrinkMap.put(photoItem7.pointList.get(0), new PointF(2.0f, 1.0f));
        photoItem7.shrinkMap.put(photoItem7.pointList.get(1), new PointF(1.0f, 1.0f));
        photoItem7.shrinkMap.put(photoItem7.pointList.get(2), new PointF(1.0f, 2.0f));
        photoItem7.shrinkMap.put(photoItem7.pointList.get(3), new PointF(2.0f, 2.0f));
        collage.getPhotoItemList().add(photoItem7);
        PhotoItem photoItem8 = new PhotoItem();
        photoItem8.index = 6;
        photoItem8.shrinkMethod = 5;
        photoItem8.bound.set(0.3333f, 0.6666f, 0.6666f, 1.0f);
        photoItem8.pointList.add(new PointF(0.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 0.0f));
        photoItem8.pointList.add(new PointF(0.8f, 1.0f));
        photoItem8.pointList.add(new PointF(0.2f, 1.0f));
        photoItem8.shrinkMap = new HashMap<>();
        photoItem8.shrinkMap.put(photoItem8.pointList.get(0), new PointF(1.0f, 1.0f));
        photoItem8.shrinkMap.put(photoItem8.pointList.get(1), new PointF(1.0f, 1.0f));
        photoItem8.shrinkMap.put(photoItem8.pointList.get(2), new PointF(1.0f, 2.0f));
        photoItem8.shrinkMap.put(photoItem8.pointList.get(3), new PointF(2.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem8);
        PhotoItem photoItem9 = new PhotoItem();
        photoItem9.index = 7;
        photoItem9.shrinkMethod = 5;
        photoItem9.bound.set(0.6f, 0.6666f, 1.0f, 1.0f);
        photoItem9.pointList.add(new PointF(0.1666f, 0.0f));
        photoItem9.pointList.add(new PointF(1.0f, 0.0f));
        photoItem9.pointList.add(new PointF(1.0f, 1.0f));
        photoItem9.pointList.add(new PointF(0.0f, 1.0f));
        photoItem9.shrinkMap = new HashMap<>();
        photoItem9.shrinkMap.put(photoItem9.pointList.get(0), new PointF(1.0f, 1.0f));
        photoItem9.shrinkMap.put(photoItem9.pointList.get(1), new PointF(1.0f, 2.0f));
        photoItem9.shrinkMap.put(photoItem9.pointList.get(2), new PointF(2.0f, 2.0f));
        photoItem9.shrinkMap.put(photoItem9.pointList.get(3), new PointF(2.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem9);
        return collage;
    }

    static TemplateItem collage910() {
        TemplateItem collage = FrameImageUtils.collage("collage_9_10.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.shrinkMethod = 5;
        photoItem.bound.set(0.0f, 0.0f, 0.39645f, 0.39645f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(0.73881f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.6306f));
        photoItem.pointList.add(new PointF(0.6306f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 0.73881f));
        photoItem.shrinkMap = new HashMap<>();
        photoItem.shrinkMap.put(photoItem.pointList.get(0), new PointF(2.0f, 2.0f));
        photoItem.shrinkMap.put(photoItem.pointList.get(1), new PointF(2.0f, 1.0f));
        photoItem.shrinkMap.put(photoItem.pointList.get(2), new PointF(1.0f, 1.0f));
        photoItem.shrinkMap.put(photoItem.pointList.get(3), new PointF(1.0f, 1.0f));
        photoItem.shrinkMap.put(photoItem.pointList.get(4), new PointF(1.0f, 2.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.shrinkMethod = 5;
        photoItem2.bound.set(0.2929f, 0.0f, 0.7071f, 0.25f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(0.75f, 1.0f));
        photoItem2.pointList.add(new PointF(0.25f, 1.0f));
        photoItem2.shrinkMap = new HashMap<>();
        photoItem2.shrinkMap.put(photoItem2.pointList.get(0), new PointF(1.0f, 2.0f));
        photoItem2.shrinkMap.put(photoItem2.pointList.get(1), new PointF(2.0f, 1.0f));
        photoItem2.shrinkMap.put(photoItem2.pointList.get(2), new PointF(1.0f, 1.0f));
        photoItem2.shrinkMap.put(photoItem2.pointList.get(3), new PointF(1.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 8;
        photoItem3.shrinkMethod = 5;
        photoItem3.bound.set(0.60355f, 0.0f, 1.0f, 0.39645f);
        photoItem3.pointList.add(new PointF(0.26119f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.73881f));
        photoItem3.pointList.add(new PointF(0.3694f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 0.6306f));
        photoItem3.shrinkMap = new HashMap<>();
        photoItem3.shrinkMap.put(photoItem3.pointList.get(0), new PointF(1.0f, 2.0f));
        photoItem3.shrinkMap.put(photoItem3.pointList.get(1), new PointF(2.0f, 2.0f));
        photoItem3.shrinkMap.put(photoItem3.pointList.get(2), new PointF(2.0f, 1.0f));
        photoItem3.shrinkMap.put(photoItem3.pointList.get(3), new PointF(1.0f, 1.0f));
        photoItem3.shrinkMap.put(photoItem3.pointList.get(4), new PointF(1.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 2;
        photoItem4.shrinkMethod = 5;
        photoItem4.bound.set(0.75f, 0.2929f, 1.0f, 0.7071f);
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 0.75f));
        photoItem4.pointList.add(new PointF(0.0f, 0.25f));
        photoItem4.shrinkMap = new HashMap<>();
        photoItem4.shrinkMap.put(photoItem4.pointList.get(0), new PointF(1.0f, 2.0f));
        photoItem4.shrinkMap.put(photoItem4.pointList.get(1), new PointF(2.0f, 1.0f));
        photoItem4.shrinkMap.put(photoItem4.pointList.get(2), new PointF(1.0f, 1.0f));
        photoItem4.shrinkMap.put(photoItem4.pointList.get(3), new PointF(1.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 3;
        photoItem5.shrinkMethod = 5;
        photoItem5.bound.set(0.60355f, 0.60355f, 1.0f, 1.0f);
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.26199f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 0.3694f));
        photoItem5.pointList.add(new PointF(0.3694f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.26199f));
        photoItem5.shrinkMap = new HashMap<>();
        photoItem5.shrinkMap.put(photoItem5.pointList.get(0), new PointF(2.0f, 2.0f));
        photoItem5.shrinkMap.put(photoItem5.pointList.get(1), new PointF(2.0f, 1.0f));
        photoItem5.shrinkMap.put(photoItem5.pointList.get(2), new PointF(1.0f, 1.0f));
        photoItem5.shrinkMap.put(photoItem5.pointList.get(3), new PointF(1.0f, 1.0f));
        photoItem5.shrinkMap.put(photoItem5.pointList.get(4), new PointF(1.0f, 2.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 4;
        photoItem6.shrinkMethod = 5;
        photoItem6.bound.set(0.2929f, 0.75f, 0.7071f, 1.0f);
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.25f, 0.0f));
        photoItem6.pointList.add(new PointF(0.75f, 0.0f));
        photoItem6.shrinkMap = new HashMap<>();
        photoItem6.shrinkMap.put(photoItem6.pointList.get(0), new PointF(1.0f, 2.0f));
        photoItem6.shrinkMap.put(photoItem6.pointList.get(1), new PointF(2.0f, 1.0f));
        photoItem6.shrinkMap.put(photoItem6.pointList.get(2), new PointF(1.0f, 1.0f));
        photoItem6.shrinkMap.put(photoItem6.pointList.get(3), new PointF(1.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 5;
        photoItem7.shrinkMethod = 5;
        photoItem7.bound.set(0.0f, 0.60355f, 0.39645f, 1.0f);
        photoItem7.pointList.add(new PointF(0.6306f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 0.3694f));
        photoItem7.pointList.add(new PointF(0.73881f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 0.26199f));
        photoItem7.shrinkMap = new HashMap<>();
        photoItem7.shrinkMap.put(photoItem7.pointList.get(0), new PointF(1.0f, 1.0f));
        photoItem7.shrinkMap.put(photoItem7.pointList.get(1), new PointF(1.0f, 1.0f));
        photoItem7.shrinkMap.put(photoItem7.pointList.get(2), new PointF(1.0f, 2.0f));
        photoItem7.shrinkMap.put(photoItem7.pointList.get(3), new PointF(2.0f, 2.0f));
        photoItem7.shrinkMap.put(photoItem7.pointList.get(4), new PointF(2.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        PhotoItem photoItem8 = new PhotoItem();
        photoItem8.index = 6;
        photoItem8.shrinkMethod = 5;
        photoItem8.bound.set(0.0f, 0.2929f, 0.25f, 0.7071f);
        photoItem8.pointList.add(new PointF(0.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 0.25f));
        photoItem8.pointList.add(new PointF(1.0f, 0.75f));
        photoItem8.pointList.add(new PointF(0.0f, 1.0f));
        photoItem8.shrinkMap = new HashMap<>();
        photoItem8.shrinkMap.put(photoItem8.pointList.get(0), new PointF(2.0f, 1.0f));
        photoItem8.shrinkMap.put(photoItem8.pointList.get(1), new PointF(1.0f, 1.0f));
        photoItem8.shrinkMap.put(photoItem8.pointList.get(2), new PointF(1.0f, 1.0f));
        photoItem8.shrinkMap.put(photoItem8.pointList.get(3), new PointF(1.0f, 2.0f));
        collage.getPhotoItemList().add(photoItem8);
        PhotoItem photoItem9 = new PhotoItem();
        photoItem9.index = 7;
        photoItem9.shrinkMethod = 5;
        photoItem9.bound.set(0.25f, 0.25f, 0.75f, 0.75f);
        photoItem9.pointList.add(new PointF(0.2929f, 0.0f));
        photoItem9.pointList.add(new PointF(0.7071f, 0.0f));
        photoItem9.pointList.add(new PointF(1.0f, 0.2929f));
        photoItem9.pointList.add(new PointF(1.0f, 0.7071f));
        photoItem9.pointList.add(new PointF(0.7071f, 1.0f));
        photoItem9.pointList.add(new PointF(0.2929f, 1.0f));
        photoItem9.pointList.add(new PointF(0.0f, 0.7071f));
        photoItem9.pointList.add(new PointF(0.0f, 0.2929f));
        photoItem9.shrinkMap = new HashMap<>();
        photoItem9.shrinkMap.put(photoItem9.pointList.get(0), new PointF(1.0f, 1.0f));
        photoItem9.shrinkMap.put(photoItem9.pointList.get(1), new PointF(1.0f, 1.0f));
        photoItem9.shrinkMap.put(photoItem9.pointList.get(2), new PointF(1.0f, 1.0f));
        photoItem9.shrinkMap.put(photoItem9.pointList.get(3), new PointF(1.0f, 1.0f));
        photoItem9.shrinkMap.put(photoItem9.pointList.get(4), new PointF(1.0f, 1.0f));
        photoItem9.shrinkMap.put(photoItem9.pointList.get(5), new PointF(1.0f, 1.0f));
        photoItem9.shrinkMap.put(photoItem9.pointList.get(6), new PointF(1.0f, 1.0f));
        photoItem9.shrinkMap.put(photoItem9.pointList.get(7), new PointF(1.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem9);
        return collage;
    }

    static TemplateItem collage99() {
        TemplateItem collage = FrameImageUtils.collage("collage_9_9.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.shrinkMethod = 5;
        photoItem.bound.set(0.0f, 0.0f, 0.3f, 0.5f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.6f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        photoItem.shrinkMap = new HashMap<>();
        photoItem.shrinkMap.put(photoItem.pointList.get(0), new PointF(2.0f, 1.0f));
        photoItem.shrinkMap.put(photoItem.pointList.get(1), new PointF(1.0f, 1.0f));
        photoItem.shrinkMap.put(photoItem.pointList.get(2), new PointF(1.0f, 1.0f));
        photoItem.shrinkMap.put(photoItem.pointList.get(3), new PointF(1.0f, 2.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.shrinkMethod = 5;
        photoItem2.bound.set(0.0f, 0.0f, 0.5f, 0.3f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.6f, 1.0f));
        photoItem2.shrinkMap = new HashMap<>();
        photoItem2.shrinkMap.put(photoItem2.pointList.get(0), new PointF(1.0f, 2.0f));
        photoItem2.shrinkMap.put(photoItem2.pointList.get(1), new PointF(2.0f, 1.0f));
        photoItem2.shrinkMap.put(photoItem2.pointList.get(2), new PointF(1.0f, 1.0f));
        photoItem2.shrinkMap.put(photoItem2.pointList.get(3), new PointF(1.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 8;
        photoItem3.shrinkMethod = 5;
        photoItem3.bound.set(0.5f, 0.0f, 1.0f, 0.3f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(0.4f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        photoItem3.shrinkMap = new HashMap<>();
        photoItem3.shrinkMap.put(photoItem3.pointList.get(0), new PointF(1.0f, 2.0f));
        photoItem3.shrinkMap.put(photoItem3.pointList.get(1), new PointF(2.0f, 1.0f));
        photoItem3.shrinkMap.put(photoItem3.pointList.get(2), new PointF(1.0f, 1.0f));
        photoItem3.shrinkMap.put(photoItem3.pointList.get(3), new PointF(1.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 2;
        photoItem4.shrinkMethod = 5;
        photoItem4.bound.set(0.7f, 0.0f, 1.0f, 0.5f);
        photoItem4.pointList.add(new PointF(0.0f, 0.6f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        photoItem4.shrinkMap = new HashMap<>();
        photoItem4.shrinkMap.put(photoItem4.pointList.get(0), new PointF(1.0f, 1.0f));
        photoItem4.shrinkMap.put(photoItem4.pointList.get(1), new PointF(1.0f, 2.0f));
        photoItem4.shrinkMap.put(photoItem4.pointList.get(2), new PointF(2.0f, 1.0f));
        photoItem4.shrinkMap.put(photoItem4.pointList.get(3), new PointF(1.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 3;
        photoItem5.shrinkMethod = 5;
        photoItem5.bound.set(0.7f, 0.5f, 1.0f, 1.0f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 0.4f));
        photoItem5.shrinkMap = new HashMap<>();
        photoItem5.shrinkMap.put(photoItem5.pointList.get(0), new PointF(1.0f, 1.0f));
        photoItem5.shrinkMap.put(photoItem5.pointList.get(1), new PointF(1.0f, 2.0f));
        photoItem5.shrinkMap.put(photoItem5.pointList.get(2), new PointF(2.0f, 1.0f));
        photoItem5.shrinkMap.put(photoItem5.pointList.get(3), new PointF(1.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 4;
        photoItem6.shrinkMethod = 5;
        photoItem6.bound.set(0.5f, 0.7f, 1.0f, 1.0f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(0.4f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        photoItem6.shrinkMap = new HashMap<>();
        photoItem6.shrinkMap.put(photoItem6.pointList.get(0), new PointF(1.0f, 1.0f));
        photoItem6.shrinkMap.put(photoItem6.pointList.get(1), new PointF(1.0f, 1.0f));
        photoItem6.shrinkMap.put(photoItem6.pointList.get(2), new PointF(1.0f, 2.0f));
        photoItem6.shrinkMap.put(photoItem6.pointList.get(3), new PointF(2.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 5;
        photoItem7.shrinkMethod = 5;
        photoItem7.bound.set(0.0f, 0.7f, 0.5f, 1.0f);
        photoItem7.pointList.add(new PointF(0.6f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        photoItem7.shrinkMap = new HashMap<>();
        photoItem7.shrinkMap.put(photoItem7.pointList.get(0), new PointF(1.0f, 1.0f));
        photoItem7.shrinkMap.put(photoItem7.pointList.get(1), new PointF(1.0f, 1.0f));
        photoItem7.shrinkMap.put(photoItem7.pointList.get(2), new PointF(1.0f, 2.0f));
        photoItem7.shrinkMap.put(photoItem7.pointList.get(3), new PointF(2.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        PhotoItem photoItem8 = new PhotoItem();
        photoItem8.index = 6;
        photoItem8.shrinkMethod = 5;
        photoItem8.bound.set(0.0f, 0.5f, 0.3f, 1.0f);
        photoItem8.pointList.add(new PointF(0.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 0.4f));
        photoItem8.pointList.add(new PointF(0.0f, 1.0f));
        photoItem8.shrinkMap = new HashMap<>();
        photoItem8.shrinkMap.put(photoItem8.pointList.get(0), new PointF(2.0f, 1.0f));
        photoItem8.shrinkMap.put(photoItem8.pointList.get(1), new PointF(1.0f, 1.0f));
        photoItem8.shrinkMap.put(photoItem8.pointList.get(2), new PointF(1.0f, 1.0f));
        photoItem8.shrinkMap.put(photoItem8.pointList.get(3), new PointF(1.0f, 2.0f));
        collage.getPhotoItemList().add(photoItem8);
        PhotoItem photoItem9 = new PhotoItem();
        photoItem9.index = 7;
        photoItem9.bound.set(0.3f, 0.3f, 0.7f, 0.7f);
        photoItem9.pointList.add(new PointF(0.0f, 0.0f));
        photoItem9.pointList.add(new PointF(1.0f, 0.0f));
        photoItem9.pointList.add(new PointF(1.0f, 1.0f));
        photoItem9.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem9);
        return collage;
    }

    static TemplateItem collage98() {
        TemplateItem collage = FrameImageUtils.collage("collage_9_8.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.25f, 0.3333f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.25f, 0.0f, 0.5f, 0.3333f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 8;
        photoItem3.bound.set(0.5f, 0.0f, 0.75f, 0.3333f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 2;
        photoItem4.bound.set(0.75f, 0.0f, 1.0f, 0.3333f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 3;
        photoItem5.bound.set(0.0f, 0.6666f, 0.5f, 1.0f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 4;
        photoItem6.bound.set(0.5f, 0.6666f, 1.0f, 1.0f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 5;
        photoItem7.bound.set(0.0f, 0.3333f, 0.3333f, 0.6666f);
        photoItem7.pointList.add(new PointF(0.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        PhotoItem photoItem8 = new PhotoItem();
        photoItem8.index = 6;
        photoItem8.bound.set(0.3333f, 0.3333f, 0.6666f, 0.6666f);
        photoItem8.pointList.add(new PointF(0.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 1.0f));
        photoItem8.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem8);
        PhotoItem photoItem9 = new PhotoItem();
        photoItem9.index = 7;
        photoItem9.bound.set(0.6666f, 0.3333f, 1.0f, 0.6666f);
        photoItem9.pointList.add(new PointF(0.0f, 0.0f));
        photoItem9.pointList.add(new PointF(1.0f, 0.0f));
        photoItem9.pointList.add(new PointF(1.0f, 1.0f));
        photoItem9.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem9);
        return collage;
    }

    static TemplateItem collage97() {
        TemplateItem collage = FrameImageUtils.collage("collage_9_7.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.25f, 0.3333f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.25f, 0.0f, 0.5f, 0.3333f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 8;
        photoItem3.bound.set(0.5f, 0.0f, 0.75f, 0.3333f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 2;
        photoItem4.bound.set(0.75f, 0.0f, 1.0f, 0.3333f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 3;
        photoItem5.bound.set(0.0f, 0.3333f, 0.5f, 0.6666f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 4;
        photoItem6.bound.set(0.5f, 0.3333f, 1.0f, 0.6666f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 5;
        photoItem7.bound.set(0.0f, 0.6666f, 0.3333f, 1.0f);
        photoItem7.pointList.add(new PointF(0.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        PhotoItem photoItem8 = new PhotoItem();
        photoItem8.index = 6;
        photoItem8.bound.set(0.3333f, 0.6666f, 0.6666f, 1.0f);
        photoItem8.pointList.add(new PointF(0.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 1.0f));
        photoItem8.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem8);
        PhotoItem photoItem9 = new PhotoItem();
        photoItem9.index = 7;
        photoItem9.bound.set(0.6666f, 0.6666f, 1.0f, 1.0f);
        photoItem9.pointList.add(new PointF(0.0f, 0.0f));
        photoItem9.pointList.add(new PointF(1.0f, 0.0f));
        photoItem9.pointList.add(new PointF(1.0f, 1.0f));
        photoItem9.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem9);
        return collage;
    }

    static TemplateItem collage96() {
        TemplateItem collage = FrameImageUtils.collage("collage_9_6.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.2f, 1.0f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.2f, 0.0f, 0.4f, 0.5f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 8;
        photoItem3.bound.set(0.4f, 0.0f, 0.6f, 0.5f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 2;
        photoItem4.bound.set(0.6f, 0.0f, 0.8f, 0.5f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 3;
        photoItem5.bound.set(0.8f, 0.0f, 1.0f, 0.5f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 4;
        photoItem6.bound.set(0.2f, 0.5f, 0.4f, 1.0f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 5;
        photoItem7.bound.set(0.4f, 0.5f, 0.6f, 1.0f);
        photoItem7.pointList.add(new PointF(0.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        PhotoItem photoItem8 = new PhotoItem();
        photoItem8.index = 6;
        photoItem8.bound.set(0.6f, 0.5f, 0.8f, 1.0f);
        photoItem8.pointList.add(new PointF(0.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 1.0f));
        photoItem8.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem8);
        PhotoItem photoItem9 = new PhotoItem();
        photoItem9.index = 7;
        photoItem9.bound.set(0.8f, 0.5f, 1.0f, 1.0f);
        photoItem9.pointList.add(new PointF(0.0f, 0.0f));
        photoItem9.pointList.add(new PointF(1.0f, 0.0f));
        photoItem9.pointList.add(new PointF(1.0f, 1.0f));
        photoItem9.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem9);
        return collage;
    }

    static TemplateItem collage95() {
        TemplateItem collage = FrameImageUtils.collage("collage_9_5.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.3333f, 0.25f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.3333f, 0.0f, 0.6666f, 0.25f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 8;
        photoItem3.bound.set(0.6666f, 0.0f, 1.0f, 0.25f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 2;
        photoItem4.bound.set(0.0f, 0.25f, 0.3333f, 0.5f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 3;
        photoItem5.bound.set(0.3333f, 0.25f, 0.6666f, 0.5f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 4;
        photoItem6.bound.set(0.6666f, 0.25f, 1.0f, 0.5f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 5;
        photoItem7.bound.set(0.0f, 0.5f, 0.6666f, 1.0f);
        photoItem7.pointList.add(new PointF(0.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        PhotoItem photoItem8 = new PhotoItem();
        photoItem8.index = 6;
        photoItem8.bound.set(0.6666f, 0.5f, 1.0f, 0.75f);
        photoItem8.pointList.add(new PointF(0.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 1.0f));
        photoItem8.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem8);
        PhotoItem photoItem9 = new PhotoItem();
        photoItem9.index = 7;
        photoItem9.bound.set(0.6666f, 0.75f, 1.0f, 1.0f);
        photoItem9.pointList.add(new PointF(0.0f, 0.0f));
        photoItem9.pointList.add(new PointF(1.0f, 0.0f));
        photoItem9.pointList.add(new PointF(1.0f, 1.0f));
        photoItem9.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem9);
        return collage;
    }

    static TemplateItem collage94() {
        TemplateItem collage = FrameImageUtils.collage("collage_9_4.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.3333f, 0.3333f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.3333f, 0.0f, 1.0f, 0.3333f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.0f, 0.3333f, 0.25f, 1.0f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.25f, 0.3333f, 0.5f, 0.6666f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.5f, 0.3333f, 0.75f, 0.6666f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.75f, 0.3333f, 1.0f, 0.6666f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 6;
        photoItem7.bound.set(0.25f, 0.6666f, 0.5f, 1.0f);
        photoItem7.pointList.add(new PointF(0.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        PhotoItem photoItem8 = new PhotoItem();
        photoItem8.index = 7;
        photoItem8.bound.set(0.5f, 0.6666f, 0.75f, 1.0f);
        photoItem8.pointList.add(new PointF(0.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 1.0f));
        photoItem8.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem8);
        PhotoItem photoItem9 = new PhotoItem();
        photoItem9.index = 8;
        photoItem9.bound.set(0.75f, 0.6666f, 1.0f, 1.0f);
        photoItem9.pointList.add(new PointF(0.0f, 0.0f));
        photoItem9.pointList.add(new PointF(1.0f, 0.0f));
        photoItem9.pointList.add(new PointF(1.0f, 1.0f));
        photoItem9.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem9);
        return collage;
    }

    static TemplateItem collage93() {
        TemplateItem collage = FrameImageUtils.collage("collage_9_3.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.2f, 0.4f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.0f, 0.4f, 0.2f, 0.8f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.0f, 0.8f, 0.4f, 1.0f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.4f, 0.8f, 0.8f, 1.0f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.8f, 0.6f, 1.0f, 1.0f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.8f, 0.2f, 1.0f, 0.6f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 6;
        photoItem7.bound.set(0.2f, 0.0f, 0.6f, 0.2f);
        photoItem7.pointList.add(new PointF(0.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        PhotoItem photoItem8 = new PhotoItem();
        photoItem8.index = 7;
        photoItem8.bound.set(0.6f, 0.0f, 1.0f, 0.2f);
        photoItem8.pointList.add(new PointF(0.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 1.0f));
        photoItem8.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem8);
        PhotoItem photoItem9 = new PhotoItem();
        photoItem9.index = 8;
        photoItem9.bound.set(0.2f, 0.2f, 0.8f, 0.8f);
        photoItem9.pointList.add(new PointF(0.0f, 0.0f));
        photoItem9.pointList.add(new PointF(1.0f, 0.0f));
        photoItem9.pointList.add(new PointF(1.0f, 1.0f));
        photoItem9.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem9);
        return collage;
    }

    static TemplateItem collage92() {
        TemplateItem collage = FrameImageUtils.collage("collage_9_2.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.5f, 0.25f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.5f, 0.0f, 1.0f, 0.25f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.0f, 0.25f, 0.5f, 0.5f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.5f, 0.25f, 1.0f, 0.5f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.0f, 0.5f, 0.5f, 0.75f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.5f, 0.5f, 1.0f, 0.75f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 6;
        photoItem7.bound.set(0.0f, 0.75f, 0.3333f, 1.0f);
        photoItem7.pointList.add(new PointF(0.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        PhotoItem photoItem8 = new PhotoItem();
        photoItem8.index = 7;
        photoItem8.bound.set(0.3333f, 0.75f, 0.6666f, 1.0f);
        photoItem8.pointList.add(new PointF(0.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 1.0f));
        photoItem8.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem8);
        PhotoItem photoItem9 = new PhotoItem();
        photoItem9.index = 8;
        photoItem9.bound.set(0.6666f, 0.75f, 1.0f, 1.0f);
        photoItem9.pointList.add(new PointF(0.0f, 0.0f));
        photoItem9.pointList.add(new PointF(1.0f, 0.0f));
        photoItem9.pointList.add(new PointF(1.0f, 1.0f));
        photoItem9.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem9);
        return collage;
    }

    static TemplateItem collage91() {
        TemplateItem collage = FrameImageUtils.collage("collage_9_1.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.3333f, 0.3333f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.3333f, 0.0f, 0.6666f, 0.3333f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.6666f, 0.0f, 1.0f, 0.3333f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.0f, 0.3333f, 0.3333f, 0.6666f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.3333f, 0.3333f, 0.6666f, 0.6666f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.6666f, 0.3333f, 1.0f, 0.6666f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 6;
        photoItem7.bound.set(0.0f, 0.6666f, 0.3333f, 1.0f);
        photoItem7.pointList.add(new PointF(0.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        PhotoItem photoItem8 = new PhotoItem();
        photoItem8.index = 7;
        photoItem8.bound.set(0.3333f, 0.6666f, 0.6666f, 1.0f);
        photoItem8.pointList.add(new PointF(0.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 1.0f));
        photoItem8.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem8);
        PhotoItem photoItem9 = new PhotoItem();
        photoItem9.index = 8;
        photoItem9.bound.set(0.6666f, 0.6666f, 1.0f, 1.0f);
        photoItem9.pointList.add(new PointF(0.0f, 0.0f));
        photoItem9.pointList.add(new PointF(1.0f, 0.0f));
        photoItem9.pointList.add(new PointF(1.0f, 1.0f));
        photoItem9.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem9);
        return collage;
    }

    static TemplateItem collage90() {
        TemplateItem collage = FrameImageUtils.collage("collage_9_0.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.25f, 0.25f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.25f, 0.0f, 0.75f, 0.25f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.75f, 0.0f, 1.0f, 0.25f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.0f, 0.25f, 0.25f, 0.75f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.25f, 0.25f, 0.75f, 0.75f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.75f, 0.25f, 1.0f, 0.75f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 6;
        photoItem7.bound.set(0.0f, 0.75f, 0.25f, 1.0f);
        photoItem7.pointList.add(new PointF(0.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        PhotoItem photoItem8 = new PhotoItem();
        photoItem8.index = 7;
        photoItem8.bound.set(0.25f, 0.75f, 0.75f, 1.0f);
        photoItem8.pointList.add(new PointF(0.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 1.0f));
        photoItem8.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem8);
        PhotoItem photoItem9 = new PhotoItem();
        photoItem9.index = 8;
        photoItem9.bound.set(0.75f, 0.75f, 1.0f, 1.0f);
        photoItem9.pointList.add(new PointF(0.0f, 0.0f));
        photoItem9.pointList.add(new PointF(1.0f, 0.0f));
        photoItem9.pointList.add(new PointF(1.0f, 1.0f));
        photoItem9.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem9);
        return collage;
    }
}
