package com.sweet.selfiecameraphotoeditor.collageutils.collageviews;

import android.graphics.PointF;

import com.sweet.selfiecameraphotoeditor.collageutils.PhotoItem;
import com.sweet.selfiecameraphotoeditor.collageutils.TemplateItem;

import java.util.HashMap;

public class SevenFrameImage {
    static TemplateItem collage710() {
        TemplateItem collage = FrameImageUtils.collage("collage_7_10.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.shrinkMethod = 5;
        photoItem.bound.set(0.0f, 0.0f, 0.25f, 0.6471f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 0.7727f));
        photoItem.shrinkMap = new HashMap<>();
        photoItem.shrinkMap.put(photoItem.pointList.get(0), new PointF(2.0f, 2.0f));
        photoItem.shrinkMap.put(photoItem.pointList.get(1), new PointF(2.0f, 1.0f));
        photoItem.shrinkMap.put(photoItem.pointList.get(2), new PointF(1.0f, 1.0f));
        photoItem.shrinkMap.put(photoItem.pointList.get(3), new PointF(1.0f, 2.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.shrinkMethod = 5;
        photoItem2.bound.set(0.25f, 0.0f, 0.85f, 0.3529f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        photoItem2.shrinkMap = new HashMap<>();
        photoItem2.shrinkMap.put(photoItem2.pointList.get(0), new PointF(1.0f, 2.0f));
        photoItem2.shrinkMap.put(photoItem2.pointList.get(1), new PointF(2.0f, 1.0f));
        photoItem2.shrinkMap.put(photoItem2.pointList.get(2), new PointF(1.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.shrinkMethod = 5;
        photoItem3.bound.set(0.5f, 0.0f, 1.0f, 0.5f);
        photoItem3.pointList.add(new PointF(0.7f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 0.4118f));
        photoItem3.shrinkMap = new HashMap<>();
        photoItem3.shrinkMap.put(photoItem3.pointList.get(0), new PointF(1.0f, 2.0f));
        photoItem3.shrinkMap.put(photoItem3.pointList.get(1), new PointF(2.0f, 2.0f));
        photoItem3.shrinkMap.put(photoItem3.pointList.get(2), new PointF(2.0f, 1.0f));
        photoItem3.shrinkMap.put(photoItem3.pointList.get(3), new PointF(1.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.shrinkMethod = 5;
        photoItem4.bound.set(0.75f, 0.3529f, 1.0f, 1.0f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.2273f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        photoItem4.shrinkMap = new HashMap<>();
        photoItem4.shrinkMap.put(photoItem4.pointList.get(0), new PointF(1.0f, 1.0f));
        photoItem4.shrinkMap.put(photoItem4.pointList.get(1), new PointF(1.0f, 2.0f));
        photoItem4.shrinkMap.put(photoItem4.pointList.get(2), new PointF(2.0f, 2.0f));
        photoItem4.shrinkMap.put(photoItem4.pointList.get(3), new PointF(2.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.shrinkMethod = 5;
        photoItem5.bound.set(0.15f, 0.6471f, 0.75f, 1.0f);
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        photoItem5.shrinkMap = new HashMap<>();
        photoItem5.shrinkMap.put(photoItem5.pointList.get(0), new PointF(1.0f, 1.0f));
        photoItem5.shrinkMap.put(photoItem5.pointList.get(1), new PointF(1.0f, 2.0f));
        photoItem5.shrinkMap.put(photoItem5.pointList.get(2), new PointF(2.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.shrinkMethod = 5;
        photoItem6.bound.set(0.0f, 0.5f, 0.5f, 1.0f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.5882f));
        photoItem6.pointList.add(new PointF(0.3f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        photoItem6.shrinkMap = new HashMap<>();
        photoItem6.shrinkMap.put(photoItem6.pointList.get(0), new PointF(2.0f, 1.0f));
        photoItem6.shrinkMap.put(photoItem6.pointList.get(1), new PointF(1.0f, 1.0f));
        photoItem6.shrinkMap.put(photoItem6.pointList.get(2), new PointF(1.0f, 2.0f));
        photoItem6.shrinkMap.put(photoItem6.pointList.get(3), new PointF(2.0f, 2.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 6;
        photoItem7.shrinkMethod = 5;
        photoItem7.bound.set(0.25f, 0.2059f, 0.75f, 0.7941f);
        photoItem7.pointList.add(new PointF(0.5f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 0.25f));
        photoItem7.pointList.add(new PointF(1.0f, 0.75f));
        photoItem7.pointList.add(new PointF(0.5f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 0.75f));
        photoItem7.pointList.add(new PointF(0.0f, 0.25f));
        photoItem7.shrinkMap = new HashMap<>();
        photoItem7.shrinkMap.put(photoItem7.pointList.get(0), new PointF(1.0f, 1.0f));
        photoItem7.shrinkMap.put(photoItem7.pointList.get(1), new PointF(1.0f, 1.0f));
        photoItem7.shrinkMap.put(photoItem7.pointList.get(2), new PointF(1.0f, 1.0f));
        photoItem7.shrinkMap.put(photoItem7.pointList.get(3), new PointF(1.0f, 1.0f));
        photoItem7.shrinkMap.put(photoItem7.pointList.get(4), new PointF(1.0f, 1.0f));
        photoItem7.shrinkMap.put(photoItem7.pointList.get(5), new PointF(1.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        return collage;
    }

    static TemplateItem collage79() {
        TemplateItem collage = FrameImageUtils.collage("collage_7_9.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.3f, 0.25f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.3f, 0.0f, 0.6f, 0.25f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.0f, 0.25f, 0.3f, 1.0f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.3f, 0.25f, 0.6f, 1.0f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.6f, 0.0f, 1.0f, 0.3333f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.6f, 0.3333f, 1.0f, 0.6666f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 6;
        photoItem7.bound.set(0.6f, 0.6666f, 1.0f, 1.0f);
        photoItem7.pointList.add(new PointF(0.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        return collage;
    }

    static TemplateItem collage78() {
        TemplateItem collage = FrameImageUtils.collage("collage_7_8.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.3f, 0.75f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.3f, 0.0f, 0.6f, 0.75f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.0f, 0.75f, 0.3f, 1.0f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.3f, 0.75f, 0.6f, 1.0f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.6f, 0.0f, 1.0f, 0.3333f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.6f, 0.3333f, 1.0f, 0.6666f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 6;
        photoItem7.bound.set(0.6f, 0.6666f, 1.0f, 1.0f);
        photoItem7.pointList.add(new PointF(0.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        return collage;
    }

    static TemplateItem collage77() {
        TemplateItem collage = FrameImageUtils.collage("collage_7_7.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.6666f, 0.3333f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.6666f, 0.0f, 1.0f, 0.3333f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.0f, 0.3333f, 0.3333f, 0.6666f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.3333f, 0.3333f, 0.6666f, 0.6666f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.6666f, 0.3333f, 1.0f, 0.6666f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.0f, 0.6666f, 0.3333f, 1.0f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 6;
        photoItem7.bound.set(0.3333f, 0.6666f, 1.0f, 1.0f);
        photoItem7.pointList.add(new PointF(0.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        return collage;
    }

    static TemplateItem collage76() {
        TemplateItem collage = FrameImageUtils.collage("collage_7_6.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.6666f, 0.3333f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.0f, 0.3333f, 0.6666f, 0.6666f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.0f, 0.6666f, 0.6666f, 1.0f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.6666f, 0.0f, 1.0f, 0.25f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.6666f, 0.25f, 1.0f, 0.5f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.6666f, 0.5f, 1.0f, 0.75f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 6;
        photoItem7.bound.set(0.6666f, 0.75f, 1.0f, 1.0f);
        photoItem7.pointList.add(new PointF(0.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        return collage;
    }

    static TemplateItem collage75() {
        TemplateItem collage = FrameImageUtils.collage("collage_7_5.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.3333f, 0.3333f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.3333f, 0.0f, 0.6666f, 0.3333f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.6666f, 0.0f, 1.0f, 0.3333f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.0f, 0.3333f, 0.5f, 0.6666f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.5f, 0.3333f, 1.0f, 0.6666f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.0f, 0.6666f, 0.5f, 1.0f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 6;
        photoItem7.bound.set(0.5f, 0.6666f, 1.0f, 1.0f);
        photoItem7.pointList.add(new PointF(0.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        return collage;
    }

    static TemplateItem collage74() {
        TemplateItem collage = FrameImageUtils.collage("collage_7_4.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.3333f, 0.3333f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.3333f, 0.0f, 0.6666f, 0.3333f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.6666f, 0.0f, 1.0f, 0.3333f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.0f, 0.3333f, 0.6666f, 0.6666f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.6666f, 0.3333f, 1.0f, 0.6666f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.0f, 0.6666f, 0.6666f, 1.0f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 6;
        photoItem7.bound.set(0.6666f, 0.6666f, 1.0f, 1.0f);
        photoItem7.pointList.add(new PointF(0.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        return collage;
    }

    static TemplateItem collage73() {
        TemplateItem collage = FrameImageUtils.collage("collage_7_3.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.3333f, 0.3333f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.3333f, 0.0f, 0.6666f, 0.3333f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.6666f, 0.0f, 1.0f, 0.3333f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.0f, 0.3333f, 1.0f, 0.6666f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.0f, 0.6666f, 0.3333f, 1.0f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.3333f, 0.6666f, 0.6666f, 1.0f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 6;
        photoItem7.bound.set(0.6666f, 0.6666f, 1.0f, 1.0f);
        photoItem7.pointList.add(new PointF(0.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        return collage;
    }

    static TemplateItem collage72() {
        TemplateItem collage = FrameImageUtils.collage("collage_7_2.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 1.0f, 0.3333f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.0f, 0.3333f, 0.3333f, 0.6666f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.3333f, 0.3333f, 0.6666f, 0.6666f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.6666f, 0.3333f, 1.0f, 0.6666f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.0f, 0.6666f, 0.3333f, 1.0f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.3333f, 0.6666f, 0.6666f, 1.0f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 6;
        photoItem7.bound.set(0.6666f, 0.6666f, 1.0f, 1.0f);
        photoItem7.pointList.add(new PointF(0.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        return collage;
    }

    static TemplateItem collage71() {
        TemplateItem collage = FrameImageUtils.collage("collage_7_1.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.25f, 1.0f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.25f, 0.0f, 0.5f, 0.5f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.5f, 0.0f, 0.75f, 0.5f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.75f, 0.0f, 1.0f, 0.5f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.25f, 0.5f, 0.5f, 1.0f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.5f, 0.5f, 0.75f, 1.0f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 6;
        photoItem7.bound.set(0.75f, 0.5f, 1.0f, 1.0f);
        photoItem7.pointList.add(new PointF(0.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        return collage;
    }

    static TemplateItem collage70() {
        TemplateItem collage = FrameImageUtils.collage("collage_7_0.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.3333f, 0.3333f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.0f, 0.3333f, 0.3333f, 0.6666f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.0f, 0.6666f, 0.3333f, 1.0f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.3333f, 0.0f, 0.5555f, 0.3333f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.5555f, 0.0f, 1.0f, 0.3333f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.3333f, 0.3333f, 0.7777f, 1.0f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 6;
        photoItem7.bound.set(0.7777f, 0.3333f, 1.0f, 1.0f);
        photoItem7.pointList.add(new PointF(0.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        return collage;
    }
}
