package com.sweet.selfiecameraphotoeditor.collageutils.collageviews;

import android.graphics.PointF;

import com.sweet.selfiecameraphotoeditor.collageutils.PhotoItem;
import com.sweet.selfiecameraphotoeditor.collageutils.TemplateItem;

import java.util.HashMap;

public class SixFrameImage {
    static TemplateItem collage614() {
        TemplateItem collage = FrameImageUtils.collage("collage_6_14.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.shrinkMethod = 5;
        photoItem.bound.set(0.0f, 0.0f, 0.4f, 0.6f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.5f));
        photoItem.pointList.add(new PointF(0.625f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        photoItem.shrinkMap = new HashMap<>();
        photoItem.shrinkMap.put(photoItem.pointList.get(0), new PointF(2.0f, 2.0f));
        photoItem.shrinkMap.put(photoItem.pointList.get(1), new PointF(2.0f, 1.0f));
        photoItem.shrinkMap.put(photoItem.pointList.get(2), new PointF(1.0f, 1.0f));
        photoItem.shrinkMap.put(photoItem.pointList.get(3), new PointF(1.0f, 1.0f));
        photoItem.shrinkMap.put(photoItem.pointList.get(4), new PointF(1.0f, 2.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.shrinkMethod = 5;
        photoItem2.bound.set(0.4f, 0.0f, 1.0f, 0.3f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(0.3333f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        photoItem2.shrinkMap = new HashMap<>();
        photoItem2.shrinkMap.put(photoItem2.pointList.get(0), new PointF(1.0f, 2.0f));
        photoItem2.shrinkMap.put(photoItem2.pointList.get(1), new PointF(2.0f, 1.0f));
        photoItem2.shrinkMap.put(photoItem2.pointList.get(2), new PointF(1.0f, 1.0f));
        photoItem2.shrinkMap.put(photoItem2.pointList.get(3), new PointF(1.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.shrinkMethod = 5;
        photoItem3.bound.set(0.6f, 0.0f, 1.0f, 0.6f);
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.375f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 0.5f));
        photoItem3.shrinkMap = new HashMap<>();
        photoItem3.shrinkMap.put(photoItem3.pointList.get(0), new PointF(1.0f, 2.0f));
        photoItem3.shrinkMap.put(photoItem3.pointList.get(1), new PointF(2.0f, 1.0f));
        photoItem3.shrinkMap.put(photoItem3.pointList.get(2), new PointF(1.0f, 1.0f));
        photoItem3.shrinkMap.put(photoItem3.pointList.get(3), new PointF(1.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.shrinkMethod = 5;
        photoItem4.bound.set(0.5f, 0.6f, 1.0f, 1.0f);
        photoItem4.pointList.add(new PointF(0.5f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 0.5f));
        photoItem4.shrinkMap = new HashMap<>();
        photoItem4.shrinkMap.put(photoItem4.pointList.get(0), new PointF(1.0f, 1.0f));
        photoItem4.shrinkMap.put(photoItem4.pointList.get(1), new PointF(1.0f, 2.0f));
        photoItem4.shrinkMap.put(photoItem4.pointList.get(2), new PointF(2.0f, 2.0f));
        photoItem4.shrinkMap.put(photoItem4.pointList.get(3), new PointF(2.0f, 1.0f));
        photoItem4.shrinkMap.put(photoItem4.pointList.get(4), new PointF(1.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.shrinkMethod = 5;
        photoItem5.bound.set(0.0f, 0.6f, 0.5f, 1.0f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(0.5f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.5f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        photoItem5.shrinkMap = new HashMap<>();
        photoItem5.shrinkMap.put(photoItem5.pointList.get(0), new PointF(2.0f, 1.0f));
        photoItem5.shrinkMap.put(photoItem5.pointList.get(1), new PointF(1.0f, 1.0f));
        photoItem5.shrinkMap.put(photoItem5.pointList.get(2), new PointF(1.0f, 1.0f));
        photoItem5.shrinkMap.put(photoItem5.pointList.get(3), new PointF(1.0f, 2.0f));
        photoItem5.shrinkMap.put(photoItem5.pointList.get(4), new PointF(2.0f, 2.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.shrinkMethod = 5;
        photoItem6.bound.set(0.25f, 0.3f, 0.75f, 0.8f);
        photoItem6.pointList.add(new PointF(0.3f, 0.0f));
        photoItem6.pointList.add(new PointF(0.7f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.6f));
        photoItem6.pointList.add(new PointF(0.5f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 0.6f));
        photoItem6.shrinkMap = new HashMap<>();
        photoItem6.shrinkMap.put(photoItem6.pointList.get(0), new PointF(1.0f, 1.0f));
        photoItem6.shrinkMap.put(photoItem6.pointList.get(1), new PointF(1.0f, 1.0f));
        photoItem6.shrinkMap.put(photoItem6.pointList.get(2), new PointF(1.0f, 1.0f));
        photoItem6.shrinkMap.put(photoItem6.pointList.get(3), new PointF(1.0f, 1.0f));
        photoItem6.shrinkMap.put(photoItem6.pointList.get(4), new PointF(1.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        return collage;
    }

    static TemplateItem collage613() {
        TemplateItem collage = FrameImageUtils.collage("collage_6_13.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.shrinkMethod = 5;
        photoItem.bound.set(0.0f, 0.0f, 0.5f, 0.5f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        photoItem.shrinkMap = new HashMap<>();
        photoItem.shrinkMap.put(photoItem.pointList.get(0), new PointF(2.0f, 2.0f));
        photoItem.shrinkMap.put(photoItem.pointList.get(1), new PointF(2.0f, 1.0f));
        photoItem.shrinkMap.put(photoItem.pointList.get(2), new PointF(1.0f, 2.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.shrinkMethod = 5;
        photoItem2.bound.set(0.5f, 0.5f, 1.0f, 1.0f);
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        photoItem2.shrinkMap = new HashMap<>();
        photoItem2.shrinkMap.put(photoItem2.pointList.get(0), new PointF(1.0f, 2.0f));
        photoItem2.shrinkMap.put(photoItem2.pointList.get(1), new PointF(2.0f, 2.0f));
        photoItem2.shrinkMap.put(photoItem2.pointList.get(2), new PointF(2.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.shrinkMethod = 5;
        photoItem3.bound.set(0.35f, 0.0f, 1.0f, 0.4f);
        photoItem3.pointList.add(new PointF(0.2308f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(0.3846f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 0.375f));
        photoItem3.shrinkMap = new HashMap<>();
        photoItem3.shrinkMap.put(photoItem3.pointList.get(0), new PointF(1.0f, 2.0f));
        photoItem3.shrinkMap.put(photoItem3.pointList.get(1), new PointF(2.0f, 1.0f));
        photoItem3.shrinkMap.put(photoItem3.pointList.get(2), new PointF(1.0f, 1.0f));
        photoItem3.shrinkMap.put(photoItem3.pointList.get(3), new PointF(1.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.shrinkMethod = 5;
        photoItem4.bound.set(0.0f, 0.15f, 0.6f, 1.0f);
        photoItem4.pointList.add(new PointF(0.5833f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.2941f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 0.4118f));
        photoItem4.shrinkMap = new HashMap<>();
        photoItem4.shrinkMap.put(photoItem4.pointList.get(0), new PointF(1.0f, 1.0f));
        photoItem4.shrinkMap.put(photoItem4.pointList.get(1), new PointF(1.0f, 1.0f));
        photoItem4.shrinkMap.put(photoItem4.pointList.get(2), new PointF(1.0f, 2.0f));
        photoItem4.shrinkMap.put(photoItem4.pointList.get(3), new PointF(2.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.shrinkMethod = 5;
        photoItem5.bound.set(0.0f, 0.6f, 0.65f, 1.0f);
        photoItem5.pointList.add(new PointF(0.6154f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.625f));
        photoItem5.pointList.add(new PointF(0.7692f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        photoItem5.shrinkMap = new HashMap<>();
        photoItem5.shrinkMap.put(photoItem5.pointList.get(0), new PointF(1.0f, 1.0f));
        photoItem5.shrinkMap.put(photoItem5.pointList.get(1), new PointF(1.0f, 1.0f));
        photoItem5.shrinkMap.put(photoItem5.pointList.get(2), new PointF(1.0f, 2.0f));
        photoItem5.shrinkMap.put(photoItem5.pointList.get(3), new PointF(2.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.shrinkMethod = 5;
        photoItem6.bound.set(0.4f, 0.0f, 1.0f, 0.85f);
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.5882f));
        photoItem6.pointList.add(new PointF(0.4166f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 0.7059f));
        photoItem6.shrinkMap = new HashMap<>();
        photoItem6.shrinkMap.put(photoItem6.pointList.get(0), new PointF(1.0f, 2.0f));
        photoItem6.shrinkMap.put(photoItem6.pointList.get(1), new PointF(2.0f, 1.0f));
        photoItem6.shrinkMap.put(photoItem6.pointList.get(2), new PointF(1.0f, 1.0f));
        photoItem6.shrinkMap.put(photoItem6.pointList.get(3), new PointF(1.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        return collage;
    }

    static TemplateItem collage612() {
        TemplateItem collage = FrameImageUtils.collage("collage_6_12.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 1.0f, 0.2f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.0f, 0.2f, 0.3333f, 0.7f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.3333f, 0.2f, 0.6666f, 0.7f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.6666f, 0.2f, 1.0f, 0.7f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.0f, 0.7f, 0.5f, 1.0f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.5f, 0.7f, 1.0f, 1.0f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        return collage;
    }

    static TemplateItem collage611() {
        TemplateItem collage = FrameImageUtils.collage("collage_6_11.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 1.0f, 0.25f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.0f, 0.25f, 0.5f, 0.5f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.5f, 0.25f, 1.0f, 0.5f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.0f, 0.5f, 0.5f, 0.75f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.5f, 0.5f, 1.0f, 0.75f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.0f, 0.75f, 1.0f, 1.0f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        return collage;
    }

    static TemplateItem collage610() {
        TemplateItem collage = FrameImageUtils.collage("collage_6_10.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.6666f, 0.25f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.0f, 0.25f, 0.6666f, 0.5f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.0f, 0.5f, 0.6666f, 0.75f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.0f, 0.75f, 0.6666f, 1.0f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.6666f, 0.0f, 1.0f, 0.25f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.6666f, 0.25f, 1.0f, 1.0f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        return collage;
    }

    static TemplateItem collage69() {
        TemplateItem collage = FrameImageUtils.collage("collage_6_9.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.3333f, 0.3333f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.3333f, 0.0f, 0.6666f, 0.3333f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.6666f, 0.0f, 1.0f, 0.3333f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.0f, 0.3333f, 0.6666f, 1.0f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.6666f, 0.3333f, 1.0f, 0.6666f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.6666f, 0.6666f, 1.0f, 1.0f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        return collage;
    }

    static TemplateItem collage68() {
        TemplateItem collage = FrameImageUtils.collage("collage_6_8.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.3333f, 0.5f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.3333f, 0.0f, 0.6666f, 0.5f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.6666f, 0.0f, 1.0f, 0.5f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.0f, 0.5f, 0.3333f, 1.0f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.3333f, 0.5f, 0.6666f, 1.0f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.6666f, 0.5f, 1.0f, 1.0f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        return collage;
    }

    static TemplateItem collage67() {
        TemplateItem collage = FrameImageUtils.collage("collage_6_7.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.3333f, 0.3333f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.0f, 0.3333f, 0.3333f, 0.6666f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.0f, 0.6666f, 0.3333f, 1.0f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.3333f, 0.4f, 1.0f, 1.0f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.3333f, 0.0f, 0.6666f, 0.4f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.6666f, 0.0f, 1.0f, 0.4f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        return collage;
    }

    static TemplateItem collage66() {
        TemplateItem collage = FrameImageUtils.collage("collage_6_6.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.25f, 0.3333f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.25f, 0.0f, 0.5f, 0.3333f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.5f, 0.0f, 1.0f, 0.6666f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.0f, 0.3333f, 0.5f, 1.0f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.5f, 0.6666f, 0.75f, 1.0f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.75f, 0.6666f, 1.0f, 1.0f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        return collage;
    }

    static TemplateItem collage65() {
        TemplateItem collage = FrameImageUtils.collage("collage_6_5.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.6667f, 0.3333f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.6667f, 0.0f, 1.0f, 0.3333f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.0f, 0.3333f, 0.3333f, 0.6666f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.3333f, 0.3333f, 1.0f, 0.6666f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.0f, 0.6666f, 0.6667f, 1.0f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.6667f, 0.6666f, 1.0f, 1.0f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        return collage;
    }

    static TemplateItem collage64() {
        TemplateItem collage = FrameImageUtils.collage("collage_6_4.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.5f, 0.3333f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.5f, 0.0f, 1.0f, 0.3333f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.0f, 0.3333f, 0.5f, 0.6666f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.5f, 0.3333f, 1.0f, 0.6666f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.0f, 0.6666f, 0.5f, 1.0f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.5f, 0.6666f, 1.0f, 1.0f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        return collage;
    }

    static TemplateItem collage63() {
        TemplateItem collage = FrameImageUtils.collage("collage_6_3.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.3333f, 0.3333f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.3333f, 0.0f, 1.0f, 0.3333f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.0f, 0.3333f, 0.3333f, 0.6666f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.3333f, 0.3333f, 1.0f, 0.6666f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.0f, 0.6666f, 0.3333f, 1.0f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.3333f, 0.6666f, 1.0f, 1.0f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        return collage;
    }

    static TemplateItem collage62() {
        TemplateItem collage = FrameImageUtils.collage("collage_6_2.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.3333f, 0.3333f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.3333f, 0.0f, 1.0f, 0.3333f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.0f, 0.3333f, 0.5f, 0.6666f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.5f, 0.3333f, 1.0f, 0.6666f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.0f, 0.6666f, 0.3333f, 1.0f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.3333f, 0.6666f, 1.0f, 1.0f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        return collage;
    }

    static TemplateItem collage61() {
        TemplateItem collage = FrameImageUtils.collage("collage_6_1.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.3333f, 0.3333f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.3333f, 0.0f, 1.0f, 0.3333f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.0f, 0.3333f, 0.5f, 0.6666f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.5f, 0.3333f, 1.0f, 0.6666f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.0f, 0.6666f, 0.6666f, 1.0f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.6666f, 0.6666f, 1.0f, 1.0f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        return collage;
    }

    static TemplateItem collage60() {
        TemplateItem collage = FrameImageUtils.collage("collage_6_0.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.3333f, 0.6667f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.0f, 0.6667f, 0.3333f, 1.0f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.3333f, 0.0f, 1.0f, 0.3333f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.3333f, 0.3333f, 1.0f, 0.6667f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.3333f, 0.6666f, 0.6667f, 1.0f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.6666f, 0.6666f, 1.0f, 1.0f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        return collage;
    }
}
