package com.sweet.selfiecameraphotoeditor.collageutils.collageviews;

import android.graphics.PointF;

import com.sweet.selfiecameraphotoeditor.collageutils.PhotoItem;
import com.sweet.selfiecameraphotoeditor.collageutils.TemplateItem;

public class TenFrameImage {
    static TemplateItem collage108() {
        TemplateItem collage = FrameImageUtils.collage("collage_10_8.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.2f, 0.2f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.2f, 0.0f, 1.0f, 0.2f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.0f, 0.2f, 0.2f, 0.5f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.2f, 0.2f, 0.5f, 0.8f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.5f, 0.2f, 0.8f, 0.8f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.0f, 0.5f, 0.2f, 0.8f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 6;
        photoItem7.bound.set(0.8f, 0.2f, 1.0f, 0.5f);
        photoItem7.pointList.add(new PointF(0.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        PhotoItem photoItem8 = new PhotoItem();
        photoItem8.index = 7;
        photoItem8.bound.set(0.8f, 0.5f, 1.0f, 0.8f);
        photoItem8.pointList.add(new PointF(0.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 1.0f));
        photoItem8.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem8);
        PhotoItem photoItem9 = new PhotoItem();
        photoItem9.index = 8;
        photoItem9.bound.set(0.0f, 0.8f, 0.8f, 1.0f);
        photoItem9.pointList.add(new PointF(0.0f, 0.0f));
        photoItem9.pointList.add(new PointF(1.0f, 0.0f));
        photoItem9.pointList.add(new PointF(1.0f, 1.0f));
        photoItem9.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem9);
        PhotoItem photoItem10 = new PhotoItem();
        photoItem10.index = 9;
        photoItem10.bound.set(0.8f, 0.8f, 1.0f, 1.0f);
        photoItem10.pointList.add(new PointF(0.0f, 0.0f));
        photoItem10.pointList.add(new PointF(1.0f, 0.0f));
        photoItem10.pointList.add(new PointF(1.0f, 1.0f));
        photoItem10.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem10);
        return collage;
    }

    static TemplateItem collage107() {
        TemplateItem collage = FrameImageUtils.collage("collage_10_7.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.2f, 0.2f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.2f, 0.0f, 1.0f, 0.2f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.0f, 0.2f, 0.2f, 0.5f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.2f, 0.2f, 0.6f, 0.5f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.6f, 0.2f, 1.0f, 0.5f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.0f, 0.5f, 0.2f, 0.8f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 6;
        photoItem7.bound.set(0.2f, 0.5f, 0.6f, 0.8f);
        photoItem7.pointList.add(new PointF(0.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        PhotoItem photoItem8 = new PhotoItem();
        photoItem8.index = 7;
        photoItem8.bound.set(0.6f, 0.5f, 1.0f, 0.8f);
        photoItem8.pointList.add(new PointF(0.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 1.0f));
        photoItem8.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem8);
        PhotoItem photoItem9 = new PhotoItem();
        photoItem9.index = 8;
        photoItem9.bound.set(0.0f, 0.8f, 0.6f, 1.0f);
        photoItem9.pointList.add(new PointF(0.0f, 0.0f));
        photoItem9.pointList.add(new PointF(1.0f, 0.0f));
        photoItem9.pointList.add(new PointF(1.0f, 1.0f));
        photoItem9.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem9);
        PhotoItem photoItem10 = new PhotoItem();
        photoItem10.index = 9;
        photoItem10.bound.set(0.6f, 0.8f, 1.0f, 1.0f);
        photoItem10.pointList.add(new PointF(0.0f, 0.0f));
        photoItem10.pointList.add(new PointF(1.0f, 0.0f));
        photoItem10.pointList.add(new PointF(1.0f, 1.0f));
        photoItem10.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem10);
        return collage;
    }

    static TemplateItem collage106() {
        TemplateItem collage = FrameImageUtils.collage("collage_10_6.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.5f, 0.25f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.5f, 0.0f, 1.0f, 0.25f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.0f, 0.25f, 0.25f, 0.75f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.25f, 0.25f, 0.5f, 0.5f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.5f, 0.25f, 0.75f, 0.5f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.25f, 0.5f, 0.5f, 0.75f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 6;
        photoItem7.bound.set(0.5f, 0.5f, 0.75f, 0.75f);
        photoItem7.pointList.add(new PointF(0.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        PhotoItem photoItem8 = new PhotoItem();
        photoItem8.index = 7;
        photoItem8.bound.set(0.75f, 0.25f, 1.0f, 0.75f);
        photoItem8.pointList.add(new PointF(0.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 1.0f));
        photoItem8.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem8);
        PhotoItem photoItem9 = new PhotoItem();
        photoItem9.index = 8;
        photoItem9.bound.set(0.0f, 0.75f, 0.5f, 1.0f);
        photoItem9.pointList.add(new PointF(0.0f, 0.0f));
        photoItem9.pointList.add(new PointF(1.0f, 0.0f));
        photoItem9.pointList.add(new PointF(1.0f, 1.0f));
        photoItem9.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem9);
        PhotoItem photoItem10 = new PhotoItem();
        photoItem10.index = 9;
        photoItem10.bound.set(0.5f, 0.75f, 1.0f, 1.0f);
        photoItem10.pointList.add(new PointF(0.0f, 0.0f));
        photoItem10.pointList.add(new PointF(1.0f, 0.0f));
        photoItem10.pointList.add(new PointF(1.0f, 1.0f));
        photoItem10.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem10);
        return collage;
    }

    static TemplateItem collage105() {
        TemplateItem collage = FrameImageUtils.collage("collage_10_5.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.5f, 0.25f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.5f, 0.0f, 1.0f, 0.25f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.0f, 0.25f, 0.2f, 0.5f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.2f, 0.25f, 0.8f, 0.5f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.8f, 0.25f, 1.0f, 0.5f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.0f, 0.5f, 0.2f, 0.75f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 6;
        photoItem7.bound.set(0.2f, 0.5f, 0.8f, 0.75f);
        photoItem7.pointList.add(new PointF(0.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        PhotoItem photoItem8 = new PhotoItem();
        photoItem8.index = 7;
        photoItem8.bound.set(0.8f, 0.5f, 1.0f, 0.75f);
        photoItem8.pointList.add(new PointF(0.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 1.0f));
        photoItem8.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem8);
        PhotoItem photoItem9 = new PhotoItem();
        photoItem9.index = 8;
        photoItem9.bound.set(0.0f, 0.75f, 0.5f, 1.0f);
        photoItem9.pointList.add(new PointF(0.0f, 0.0f));
        photoItem9.pointList.add(new PointF(1.0f, 0.0f));
        photoItem9.pointList.add(new PointF(1.0f, 1.0f));
        photoItem9.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem9);
        PhotoItem photoItem10 = new PhotoItem();
        photoItem10.index = 9;
        photoItem10.bound.set(0.5f, 0.75f, 1.0f, 1.0f);
        photoItem10.pointList.add(new PointF(0.0f, 0.0f));
        photoItem10.pointList.add(new PointF(1.0f, 0.0f));
        photoItem10.pointList.add(new PointF(1.0f, 1.0f));
        photoItem10.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem10);
        return collage;
    }

    static TemplateItem collage104() {
        TemplateItem collage = FrameImageUtils.collage("collage_10_4.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.5f, 0.5f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.0f, 0.5f, 0.5f, 1.0f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.5f, 0.0f, 0.8f, 0.2f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.8f, 0.0f, 1.0f, 0.2f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.5f, 0.2f, 0.8f, 0.5f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.8f, 0.2f, 1.0f, 0.5f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 6;
        photoItem7.bound.set(0.5f, 0.5f, 0.8f, 0.8f);
        photoItem7.pointList.add(new PointF(0.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        PhotoItem photoItem8 = new PhotoItem();
        photoItem8.index = 7;
        photoItem8.bound.set(0.8f, 0.5f, 1.0f, 0.8f);
        photoItem8.pointList.add(new PointF(0.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 1.0f));
        photoItem8.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem8);
        PhotoItem photoItem9 = new PhotoItem();
        photoItem9.index = 8;
        photoItem9.bound.set(0.5f, 0.8f, 0.8f, 1.0f);
        photoItem9.pointList.add(new PointF(0.0f, 0.0f));
        photoItem9.pointList.add(new PointF(1.0f, 0.0f));
        photoItem9.pointList.add(new PointF(1.0f, 1.0f));
        photoItem9.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem9);
        PhotoItem photoItem10 = new PhotoItem();
        photoItem10.index = 9;
        photoItem10.bound.set(0.8f, 0.8f, 1.0f, 1.0f);
        photoItem10.pointList.add(new PointF(0.0f, 0.0f));
        photoItem10.pointList.add(new PointF(1.0f, 0.0f));
        photoItem10.pointList.add(new PointF(1.0f, 1.0f));
        photoItem10.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem10);
        return collage;
    }

    static TemplateItem collage103() {
        TemplateItem collage = FrameImageUtils.collage("collage_10_3.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.7f, 0.3f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.7f, 0.0f, 1.0f, 0.3f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.0f, 0.3f, 0.7f, 0.7f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.7f, 0.3f, 0.9f, 0.7f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.9f, 0.3f, 1.0f, 0.7f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.0f, 0.7f, 0.3f, 0.9f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 6;
        photoItem7.bound.set(0.0f, 0.9f, 0.3f, 1.0f);
        photoItem7.pointList.add(new PointF(0.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        PhotoItem photoItem8 = new PhotoItem();
        photoItem8.index = 7;
        photoItem8.bound.set(0.3f, 0.7f, 0.7f, 1.0f);
        photoItem8.pointList.add(new PointF(0.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 1.0f));
        photoItem8.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem8);
        PhotoItem photoItem9 = new PhotoItem();
        photoItem9.index = 8;
        photoItem9.bound.set(0.7f, 0.7f, 1.0f, 0.9f);
        photoItem9.pointList.add(new PointF(0.0f, 0.0f));
        photoItem9.pointList.add(new PointF(1.0f, 0.0f));
        photoItem9.pointList.add(new PointF(1.0f, 1.0f));
        photoItem9.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem9);
        PhotoItem photoItem10 = new PhotoItem();
        photoItem10.index = 9;
        photoItem10.bound.set(0.7f, 0.9f, 1.0f, 1.0f);
        photoItem10.pointList.add(new PointF(0.0f, 0.0f));
        photoItem10.pointList.add(new PointF(1.0f, 0.0f));
        photoItem10.pointList.add(new PointF(1.0f, 1.0f));
        photoItem10.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem10);
        return collage;
    }

    static TemplateItem collage102() {
        TemplateItem collage = FrameImageUtils.collage("collage_10_2.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.5f, 0.5f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.5f, 0.0f, 1.0f, 0.5f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.0f, 0.5f, 0.2f, 0.8f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.2f, 0.5f, 0.5f, 0.8f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.5f, 0.5f, 0.8f, 0.8f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.8f, 0.5f, 1.0f, 0.8f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 6;
        photoItem7.bound.set(0.0f, 0.8f, 0.2f, 1.0f);
        photoItem7.pointList.add(new PointF(0.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        PhotoItem photoItem8 = new PhotoItem();
        photoItem8.index = 7;
        photoItem8.bound.set(0.2f, 0.8f, 0.5f, 1.0f);
        photoItem8.pointList.add(new PointF(0.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 1.0f));
        photoItem8.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem8);
        PhotoItem photoItem9 = new PhotoItem();
        photoItem9.index = 8;
        photoItem9.bound.set(0.5f, 0.8f, 0.8f, 1.0f);
        photoItem9.pointList.add(new PointF(0.0f, 0.0f));
        photoItem9.pointList.add(new PointF(1.0f, 0.0f));
        photoItem9.pointList.add(new PointF(1.0f, 1.0f));
        photoItem9.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem9);
        PhotoItem photoItem10 = new PhotoItem();
        photoItem10.index = 9;
        photoItem10.bound.set(0.8f, 0.8f, 1.0f, 1.0f);
        photoItem10.pointList.add(new PointF(0.0f, 0.0f));
        photoItem10.pointList.add(new PointF(1.0f, 0.0f));
        photoItem10.pointList.add(new PointF(1.0f, 1.0f));
        photoItem10.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem10);
        return collage;
    }

    static TemplateItem collage101() {
        TemplateItem collage = FrameImageUtils.collage("collage_10_1.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.25f, 0.3333f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.25f, 0.0f, 0.75f, 0.3333f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.75f, 0.0f, 1.0f, 0.3333f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.0f, 0.3333f, 0.25f, 0.6666f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.25f, 0.3333f, 0.5f, 0.6666f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.5f, 0.3333f, 0.75f, 0.6666f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 6;
        photoItem7.bound.set(0.75f, 0.3333f, 1.0f, 0.6666f);
        photoItem7.pointList.add(new PointF(0.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        PhotoItem photoItem8 = new PhotoItem();
        photoItem8.index = 7;
        photoItem8.bound.set(0.0f, 0.6666f, 0.25f, 1.0f);
        photoItem8.pointList.add(new PointF(0.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 1.0f));
        photoItem8.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem8);
        PhotoItem photoItem9 = new PhotoItem();
        photoItem9.index = 8;
        photoItem9.bound.set(0.25f, 0.6666f, 0.75f, 1.0f);
        photoItem9.pointList.add(new PointF(0.0f, 0.0f));
        photoItem9.pointList.add(new PointF(1.0f, 0.0f));
        photoItem9.pointList.add(new PointF(1.0f, 1.0f));
        photoItem9.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem9);
        PhotoItem photoItem10 = new PhotoItem();
        photoItem10.index = 9;
        photoItem10.bound.set(0.75f, 0.6666f, 1.0f, 1.0f);
        photoItem10.pointList.add(new PointF(0.0f, 0.0f));
        photoItem10.pointList.add(new PointF(1.0f, 0.0f));
        photoItem10.pointList.add(new PointF(1.0f, 1.0f));
        photoItem10.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem10);
        return collage;
    }

    static TemplateItem collage100() {
        TemplateItem collage = FrameImageUtils.collage("collage_10_0.png");
        PhotoItem photoItem = new PhotoItem();
        photoItem.index = 0;
        photoItem.bound.set(0.0f, 0.0f, 0.2f, 0.2f);
        photoItem.pointList.add(new PointF(0.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 0.0f));
        photoItem.pointList.add(new PointF(1.0f, 1.0f));
        photoItem.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem);
        PhotoItem photoItem2 = new PhotoItem();
        photoItem2.index = 1;
        photoItem2.bound.set(0.2f, 0.0f, 0.8f, 0.2f);
        photoItem2.pointList.add(new PointF(0.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 0.0f));
        photoItem2.pointList.add(new PointF(1.0f, 1.0f));
        photoItem2.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem2);
        PhotoItem photoItem3 = new PhotoItem();
        photoItem3.index = 2;
        photoItem3.bound.set(0.8f, 0.0f, 1.0f, 0.2f);
        photoItem3.pointList.add(new PointF(0.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 0.0f));
        photoItem3.pointList.add(new PointF(1.0f, 1.0f));
        photoItem3.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem3);
        PhotoItem photoItem4 = new PhotoItem();
        photoItem4.index = 3;
        photoItem4.bound.set(0.0f, 0.2f, 0.2f, 0.8f);
        photoItem4.pointList.add(new PointF(0.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 0.0f));
        photoItem4.pointList.add(new PointF(1.0f, 1.0f));
        photoItem4.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem4);
        PhotoItem photoItem5 = new PhotoItem();
        photoItem5.index = 4;
        photoItem5.bound.set(0.0f, 0.8f, 0.2f, 1.0f);
        photoItem5.pointList.add(new PointF(0.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 0.0f));
        photoItem5.pointList.add(new PointF(1.0f, 1.0f));
        photoItem5.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem5);
        PhotoItem photoItem6 = new PhotoItem();
        photoItem6.index = 5;
        photoItem6.bound.set(0.2f, 0.8f, 0.8f, 1.0f);
        photoItem6.pointList.add(new PointF(0.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 0.0f));
        photoItem6.pointList.add(new PointF(1.0f, 1.0f));
        photoItem6.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem6);
        PhotoItem photoItem7 = new PhotoItem();
        photoItem7.index = 6;
        photoItem7.bound.set(0.8f, 0.8f, 1.0f, 1.0f);
        photoItem7.pointList.add(new PointF(0.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 0.0f));
        photoItem7.pointList.add(new PointF(1.0f, 1.0f));
        photoItem7.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem7);
        PhotoItem photoItem8 = new PhotoItem();
        photoItem8.index = 7;
        photoItem8.bound.set(0.8f, 0.2f, 1.0f, 0.8f);
        photoItem8.pointList.add(new PointF(0.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 0.0f));
        photoItem8.pointList.add(new PointF(1.0f, 1.0f));
        photoItem8.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem8);
        PhotoItem photoItem9 = new PhotoItem();
        photoItem9.index = 8;
        photoItem9.bound.set(0.2f, 0.2f, 0.8f, 0.5f);
        photoItem9.pointList.add(new PointF(0.0f, 0.0f));
        photoItem9.pointList.add(new PointF(1.0f, 0.0f));
        photoItem9.pointList.add(new PointF(1.0f, 1.0f));
        photoItem9.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem9);
        PhotoItem photoItem10 = new PhotoItem();
        photoItem10.index = 9;
        photoItem10.bound.set(0.2f, 0.5f, 0.8f, 0.8f);
        photoItem10.pointList.add(new PointF(0.0f, 0.0f));
        photoItem10.pointList.add(new PointF(1.0f, 0.0f));
        photoItem10.pointList.add(new PointF(1.0f, 1.0f));
        photoItem10.pointList.add(new PointF(0.0f, 1.0f));
        collage.getPhotoItemList().add(photoItem10);
        return collage;
    }
}
